<?php

/**
 * Official state monthly targets (M1–M12) — State Target Month Wise.xlsx
 * Generated from official Excel — do not upload Excel on server.
 * Regenerate: python3 scripts/generate_official_monthly_configs.py
 */
return [
    'rows' => [
        [
            'row_type' => 'category',
            'serial' => '1',
            'name' => 'Outreach and Mobilisation',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '1',
            'serial' => '1.1',
            'name' => 'Call for Application',
            'total' => 28000,
            'indicator_type' => 'Key Indicator',
            'months' => [4550, 5040, 5600, 1820, 1470, 1470, 2030, 1770, 1245, 1045, 980, 980],
            'remark' => '28000',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '2',
            'serial' => '1.2',
            'name' => 'District Level Workshops',
            'total' => 52,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 13, 0, 13, 0, 0, 13, 0, 0, 13, 0, 0],
            'remark' => '52',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '3',
            'serial' => '1.3',
            'name' => 'No. of Awareness cum Outreach activities for SHG members/Potential Lakhpati Didis/ SHGs/CBOs etc.',
            'total' => 1352,
            'indicator_type' => 'Non-Key',
            'months' => [0, 122, 132, 122, 122, 122, 122, 122, 122, 122, 122, 122],
            'remark' => '1352',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '4',
            'serial' => '1.3.1',
            'name' => 'Participants in Awareness cum Outreach activities',
            'total' => 10000,
            'indicator_type' => 'Non-Key',
            'months' => [0, 810, 810, 860, 910, 910, 910, 940, 970, 970, 970, 940],
            'remark' => '10000',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '5',
            'serial' => '1.4',
            'name' => 'EAP/EDP Sessions',
            'total' => 156,
            'indicator_type' => 'Key Indicator',
            'months' => [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
            'remark' => '156',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '6',
            'serial' => '1.5',
            'name' => 'Outreach through Community Organizations',
            'total' => 40,
            'indicator_type' => 'Non-Key',
            'months' => [0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
            'remark' => '40',
        ],
        [
            'row_type' => 'category',
            'serial' => '2',
            'name' => 'Identification and Onboarding of Enterprises',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '7',
            'serial' => '2.1',
            'name' => 'Incubatees Onboarded',
            'total' => 7000,
            'indicator_type' => 'Key Indicator',
            'months' => [550, 650, 700, 700, 700, 800, 600, 600, 500, 400, 400, 400],
            'remark' => '7000',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '8',
            'serial' => '2.1.1',
            'name' => 'Onboarding of Potential Lakhpati Didi/ SHG Members/ CBOs*',
            'total' => 3000,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 245, 280, 300, 300, 300, 350, 250, 250, 215, 340, 170],
            'remark' => '3000',
        ],
        [
            'row_type' => 'category',
            'serial' => '3',
            'name' => 'Training & Capacity Building',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '9',
            'serial' => '3.1',
            'name' => 'Business Skills Training Sessions',
            'total' => 350,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 26, 26, 26, 39, 39, 39, 39, 38, 26, 26, 26],
            'remark' => '350',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '10',
            'serial' => '3.2',
            'name' => 'Incubatees taken Part in Business Modules Training',
            'total' => 7000,
            'indicator_type' => 'Non-Key',
            'months' => [0, 550, 650, 700, 700, 700, 800, 600, 600, 500, 800, 400],
            'remark' => '7000',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '11',
            'serial' => '3.3',
            'name' => 'Technical Trainings to Incubatees',
            'total' => 12,
            'indicator_type' => 'Non-Key',
            'months' => [0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1],
            'remark' => '12',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '12',
            'serial' => '3.4',
            'name' => 'Capacity Building of stakeholders (REAP, USRLM, Other Line department staff)',
            'total' => 2,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
            'remark' => '2',
        ],
        [
            'row_type' => 'category',
            'serial' => '4',
            'name' => 'Business Formalization',
        ],
        [
            'row_type' => 'subcategory',
            'serial' => '4.1',
            'name' => 'Business Registeration',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '13',
            'serial' => '4.1.1',
            'name' => 'Business Registration',
            'total' => 6000,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 470, 555, 600, 600, 600, 685, 515, 515, 428, 686, 346],
            'remark' => '6000',
        ],
        [
            'row_type' => 'subcategory',
            'serial' => '4.2',
            'name' => 'Legal & Licensing Support',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '15',
            'serial' => '4.2.1',
            'name' => 'Artisan Card',
            'total' => 260,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 0],
            'remark' => '260',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '16',
            'serial' => '4.2.2',
            'name' => 'FSSAI',
            'total' => 750,
            'indicator_type' => 'Non-Key',
            'months' => [0, 60, 70, 75, 75, 75, 85, 65, 65, 55, 85, 40],
            'remark' => '750',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '17',
            'serial' => '4.2.3',
            'name' => 'UTDB',
            'total' => 280,
            'indicator_type' => 'Non-Key',
            'months' => [0, 0, 0, 20, 20, 20, 20, 50, 50, 50, 30, 20],
            'remark' => '280',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '18',
            'serial' => '4.2.4',
            'name' => 'GST Registration',
            'total' => 350,
            'indicator_type' => 'Non-Key',
            'months' => [0, 0, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35],
            'remark' => '350',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '19',
            'serial' => '4.2.5',
            'name' => 'Trademark application filling',
            'total' => 35,
            'indicator_type' => 'Non-Key',
            'months' => [0, 0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7],
            'remark' => '35',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '20',
            'serial' => '4.2.6',
            'name' => 'GI Seller Registration',
            'total' => 150,
            'indicator_type' => 'Non-Key',
            'months' => [0, 0, 45, 0, 0, 0, 45, 0, 0, 60, 0, 0],
            'remark' => '150',
        ],
        [
            'row_type' => 'subcategory',
            'serial' => '4.2.7',
            'name' => 'Advance Licensing Support (Mandi Licensing, Lab Test etc.)',
        ],
        [
            'row_type' => 'category',
            'serial' => '5',
            'name' => 'Mentorship',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '22',
            'serial' => '5.1',
            'name' => 'Specialized Mentorship Support',
            'total' => 650,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 0, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65],
            'remark' => '650',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '23',
            'serial' => '5.2',
            'name' => 'Mentorship Support through online portal',
            'total' => 0,
            'indicator_type' => 'Non-Key',
            'months' => [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            'remark' => '0',
        ],
        [
            'row_type' => 'category',
            'serial' => '6',
            'name' => 'Partnership & Forward Linkages',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '24',
            'serial' => '6.1',
            'name' => 'No of Partners outreach',
            'total' => 75,
            'indicator_type' => 'Non-Key',
            'months' => [0, 15, 15, 15, 10, 10, 10, 0, 0, 0, 0, 0],
            'remark' => '75',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '25',
            'serial' => '6.2',
            'name' => 'Marketing Partners Onboarded through (LoA/LoI/MoU)',
            'total' => 50,
            'indicator_type' => 'Non-Key',
            'months' => [0, 10, 10, 10, 10, 5, 5, 0, 0, 0, 0, 0],
            'remark' => '50',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '26',
            'serial' => '6.3',
            'name' => 'Incubatees linked to online/offline Market',
            'total' => 1500,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 0, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150],
            'remark' => '1500',
        ],
        [
            'row_type' => 'category',
            'serial' => '7',
            'name' => 'Business Acceleration Services',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '41',
            'serial' => '7.1',
            'name' => 'No of Partners outreach',
            'total' => 10,
            'indicator_type' => 'Non-Key',
            'months' => [2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0],
            'remark' => '10',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '42',
            'serial' => '7.2',
            'name' => 'Initiation of acceleration and co-incubation services',
            'total' => 1400,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 100, 100, 150, 150, 150, 150, 150, 150, 150, 150, 0],
            'remark' => '1400',
        ],
        [
            'row_type' => 'category',
            'serial' => '8',
            'name' => 'Funding & Schematic Convergence',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '27',
            'serial' => '8.1',
            'name' => 'Schematic Convergence',
            'total' => 3000,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 235, 280, 300, 300, 300, 345, 260, 250, 215, 345, 170],
            'remark' => '3000',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '31',
            'serial' => '8.2',
            'name' => 'Support to MUY Incubatee through Reap',
            'total' => 500,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 0, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
            'remark' => '500',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '28',
            'serial' => '8.3',
            'name' => 'Incubatees Pitch Deck Preparation',
            'total' => 200,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 0, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
            'remark' => '200',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '29',
            'serial' => '8.4',
            'name' => 'Demo Days',
            'total' => 15,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2],
            'remark' => '15',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '30',
            'serial' => '8.5',
            'name' => 'No of Partners outreach',
            'total' => 15,
            'indicator_type' => 'Non-Key',
            'months' => [0, 0, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0],
            'remark' => '15',
        ],
        [
            'row_type' => 'category',
            'serial' => '9',
            'name' => 'Other Support Services',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '14',
            'serial' => '9.1',
            'name' => 'Business Model Canvas',
            'total' => 6000,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 470, 555, 600, 600, 600, 685, 515, 515, 428, 686, 346],
            'remark' => '6000',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '32',
            'serial' => '9.2',
            'name' => 'Other Support Services - Labelling, Packaging, Logo Designing etc.',
            'total' => 0,
            'indicator_type' => 'Non-Key',
            'months' => [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            'remark' => '0',
        ],
        [
            'row_type' => 'category',
            'serial' => '10',
            'name' => 'Branding, Communication & Knowledge Management',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '35',
            'serial' => '10.1',
            'name' => 'Social Media Post',
            'total' => 150,
            'indicator_type' => 'Key Indicator',
            'months' => [10, 10, 10, 10, 10, 10, 15, 15, 15, 15, 15, 15],
            'remark' => '150',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '36',
            'serial' => '10.2',
            'name' => 'Preparation of Case Studies and Testimonials',
            'total' => 100,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
            'remark' => '100',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '37',
            'serial' => '10.3',
            'name' => 'MUY Newsletter',
            'total' => 4,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1],
            'remark' => '4',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '38',
            'serial' => '10.4',
            'name' => 'Newspaper Ads and Radio promotion campaigns',
            'total' => 4,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0],
            'remark' => '4',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '39',
            'serial' => '10.5',
            'name' => 'Buyer-Seller Meet',
            'total' => 9,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 1],
            'remark' => '9',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '40',
            'serial' => '10.6',
            'name' => 'Events/ Seminars/ Workshops',
            'total' => 5,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2],
            'remark' => '5',
        ],
        [
            'row_type' => 'category',
            'serial' => '11',
            'name' => 'Product Development',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '43',
            'serial' => '11.1',
            'name' => 'Identification and Submission of Proposal for New Product Development',
            'total' => 10,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0],
            'remark' => '10',
        ],
        [
            'row_type' => 'category',
            'serial' => '12',
            'name' => 'Synergies Across Line Departments',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '33',
            'serial' => '12.1',
            'name' => 'Stakeholder Consultation Workshop',
            'total' => 2,
            'indicator_type' => 'Key Indicator',
            'months' => [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
            'remark' => '2',
        ],
        [
            'row_type' => 'leaf',
            'sn' => '34',
            'serial' => '12.2',
            'name' => 'Meeting of staff with Line Department at Spoke/Hub/State Level',
            'total' => 50,
            'indicator_type' => 'Non-Key',
            'months' => [0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
            'remark' => '50',
        ],
    ],
];
